### PR TITLE
Make structs private and ensure all public methods have comments

### PR DESCRIPTION
**Pull request by plasne**
This PR ensures that the structs are all private, all public things have interfaces, and that all public methods have comments.

### CODE REVIEW

**Comment by HendoCode** [comment]
Looks GTM (with some lamentations about interface naming).

**Comment by plasne** [comment]
> Looks GTM (with some lamentations about interface naming).

And by that you a referring to them starting with "i" or "I". I know it isn't go standard to do that, but frankly a lot of the objects have naming collisions without it. Plus it serves a greater purpose in the most structs would be passed as reference whereas you would never do that with an interface, so it helps clarify what is appropriate. I read the naming guide which also suggested adding -er, but then you have Batcherer and Operationer and Watcherer which makes no sense. So in short, I decided to ignore that and do what makes sense. Happy to discuss further though.

**Comment by awkwardindustries** [comment]
> > Looks GTM (with some lamentations about interface naming).
> 
> And by that you a referring to them starting with "i" or "I". I know it isn't go standard to do that, but frankly a lot of the objects have naming collisions without it. Plus it serves a greater purpose in the most structs would be passed as reference whereas you would never do that with an interface, so it helps clarify what is appropriate. I read the naming guide which also suggested adding -er, but then you have Batcherer and Operationer and Watcherer which makes no sense. So in short, I decided to ignore that and do what makes sense. Happy to discuss further though.

With this change (making the structs private), the naming collision issue goes away. You could totally have:
```go
type Batcher interface { ... }
type batcher struct { ... }
```

You're definitely continuing the convention you started with the `IBatcher`, `IWatcher`, and `IOperation` with the additional `IAzureSharedResource`, but if we should remove the `I`-for-interface to be a bit more idiomatic, we could do that now across all of those interfaces -- especially since we're prepping this release as containing breaking changes.

**Review by awkwardindustries — APPROVED** [review]
I'd consider taking this opportunity to change the interface names to be non-`I`-names since making private structs eliminates naming collisions (except for `eventer`, but that feels workaround-able since it's all private). If you'd rather leave them as `I`-prefixed, this looks good. I think it's probably more important to be consistent, but if we have an opportunity to also be more idiomatic it may be a good time to do that.

**Comment by plasne** [comment]
> I'd consider taking this opportunity to change the interface names to be non-`I`-names since making private structs eliminates naming collisions (except for `eventer`, but that feels workaround-able since it's all private). If you'd rather leave them as `I`-prefixed, this looks good. I think it's probably more important to be consistent, but if we have an opportunity to also be more idiomatic it may be a good time to do that.

Yes, agreed. That will work with everything that isn't internal (like ieventer and eventer), but those are minor cases. I will update.

**Comment by plasne** [comment]
The interfaces have had the prefixed-I removed except in the case of "eventer" and "ieventer".

**Pull request merged**
